services:
  api:
    build: .
    container_name: delivery-service-api
    command: [ "/wait-for-it.sh", "delivery-service-db:3306", "-t", "30", "--", "java", "-jar", "delivery-service-rest-api.jar" ]
    ports:
      - "8080:8080"
    environment:
      DB_HOST: delivery-service-db
      DB_PORT: 3306
      DB_SCHEMA: delivery_service_db
      DB_USER: root
      DB_PASSWORD: root
    networks:
      delivery-service-network:
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: delivery-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=delivery_service_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      delivery-service-network:

volumes:
  mysql-data:

networks:
  delivery-service-network:
    driver: bridge