server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 # 1KB

spring:
  application:
    name: delivery-service-rest-api

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:delivery_service_db}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DeliveryServiceHikariPool
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000 #30s
      connection-timeout: 20000 #20s
      max-lifetime: 1800000 #30min

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  messages:
    basename: i18n/messages